version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
init:
- cmd: yarn --version
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  NugetApi:
    secure: BRw3tw5+iSo+7oe+bzq2U64vn0QJoFH0nxvtV5FBuZgEk4zg3AZeN7dis0N05XJR
build_script:
- cmd: >-
    REM **------Publish------**
    dotnet publish ./src/IronBeard.Cli/IronBeard.Cli.csproj -c Release
after_test:
- cmd: yarn example
deploy_script:
- cmd: "if \"%APPVEYOR_REPO_TAG%\" == \"true\" ( \n  REM **------Pack------**\n  dotnet pack ./src/IronBeard.Cli/IronBeard.Cli.csproj --output ./\n\n  REM **------Push------**\n  cd src/IronBeard.Cli\n  dotnet nuget push *.nupkg -k %NugetApi% -s https://api.nuget.org/v3/index.json \n)\nelse (\n  echo \"No tag, not deploying.\"\n)"